language: java
install: true
sudo: false

jdk:
  - openjdk11

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

before_install:
  - chmod +x gradlew

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

stages:
  - name: snapshot
    if: branch == develop AND type == push
  - name: candidate
    if: branch =~ ^release\/.*$
  - name: release
    if: branch == master AND type == push
  - name: tag
    if: tag =~ ^v.*$ AND branch == master

jobs:
  include:
    - stage: snapshot
      name: "Snapshot branch"
      script:
        - ./gradlew publishToMavenLocal snapshot
        - ls -la build/libs

    - stage: candidate
      name: "Release candidate"
      script:
        - ./gradlew publishToMavenLocal candidate
        - ls -la build/libs

    - stage: release
      name: "Release"
      script:
        - ./gradlew publishToMavenLocal final
        - ls -la build/libs

    - stage: tag
      name: "Tag"
      script:
        - ./gradlew -Prelease.useLastTag=true publishToMavenLocal final
        - ls -la build/libs
