language: java
install: true
sudo: false

jdk:
  - openjdk11

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

before_install:
  - chmod +x gradlew

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

stages:
  - name: snapshot
    if: branch == develop AND type == push
  - name: candidate
    if: branch =~ ^release\/.*$
  - name: release
    if: branch == master AND type == push

jobs:
  include:
    - stage: snapshot
      name: "Snapshot branch"
      script:
        - ./gradlew clean snapshot publishToMavenLocal
        - ls -la build/libs

    - stage: candidate
      name: "Release candidate"
      script:
        - ./gradlew clean candidate publishToMavenLocal
        - ls -la build/libs

    - stage: release
      name: "Master branch"
      script:
        - ./gradlew clean final publishToMavenLocal -Prelease.useLastTag=true
        - ls -la build/libs