language: java
install: true
sudo: false

jdk:
  - openjdk11

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

before_install:
  - chmod +x gradlew

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

stages:
  - name: pr
    if: type == pull_request
  - name: snapshot
    if: branch == develop AND type == push
  - name: candidate
    if: branch =~ ^release.*$ AND type == push
  - name: release
    if: tag IS present AND branch =~ ^v.*$ AND branch =~ ^((?!rc).)*$
  - name: hotfix
    if: branch =~ ^hotfix.*$ AND type == push

jobs:
  include:
    - stage: pr
      name: "Pull request"
      script:
        - ./gradlew build test
        - ls -la build/libs

    - stage: snapshot
      name: "Snapshot branch"
      script:
        - ./gradlew snapshot
        - ls -la build/libs

    - stage: candidate
      name: "Release candidate"
      script:
        - ./gradlew candidate
        - ls -la build/libs

    - stage: release
      name: "Release on manual tag"
      script:
        - ./gradlew final -Prelease.useLastTag=true
        - ls -la build/libs

    - stage: hotfix
      name: "Hotfix"
      script:
        - ./gradlew candidate -Prelease.scope=patch
        - ls -la build/libs
